title: GOUNON Eliakim
logo: eli.jpg
description: Machine Learning Specialist,Python Developper ,NestJS
email: eliakimceleste@gmail.com
phone: "+229 0154719628"
address: "Cotonou, BENIN"
github: https://github.com/eliakimceleste
linkedin: https://linkedin.com/in/eliakimceleste
# show_downloads: true
theme: jekyll-theme-minimal
